apiVersion: apps/v1
kind: Deployment
metadata:                    #metadata is literal name of the Deployment object inside your Kubernetes cluster. open your terminal and type kubectl get deployments, this is the name that will print out on your screen.
  name: spring-boot-app
  labels:                    #labels (app: spring-boot-app) is attached to the Deployment itself, not the Pods. Why label it? For organization.
    app: spring-boot-app
spec:
  replicas: 2
  selector:                      #The selector in a Deployment is strictly for the internal manager to count the Pods and keep the replica math correct.     
    matchLabels:
      app: spring-boot-app
  template:                          #The template block is the literal blueprint for the Pods (the pop-up kitchens) that Kubernetes is going to spin up.
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: nikhilb619/ultimate-cicd:9
        ports:
        - containerPort: 8080
